-- MySQL Script generated by MySQL Workbench
-- Sat Sep  9 14:47:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `messages_sent` INT NULL,
  `messages_collected` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(256) NULL,
  `to_lat` FLOAT NULL,
  `to_lng` FLOAT NULL,
  `arrived` DATETIME NULL,
  `delivered` TINYINT(1) NULL,
  `picked_up` TINYINT(1) NULL,
  `users_id` INT NOT NULL,
  `from_lat` FLOAT NULL,
  `from_lng` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ravens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ravens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `distance_travelled` FLOAT NULL,
  `birthday` DATETIME NULL,
  `ravenscol` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  `aptitude` INT NULL,
  `messages_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ravens_users1_idx` (`users_id` ASC),
  INDEX `fk_ravens_messages1_idx` (`messages_id` ASC),
  CONSTRAINT `fk_ravens_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ravens_messages1`
    FOREIGN KEY (`messages_id`)
    REFERENCES `mydb`.`messages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
